<%@ Page Title="" Language="C#" MasterPageFile="~/ClientMasterPage.master" AutoEventWireup="true" CodeFile="About.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<!-- about breadcrumb -->
 <section class="w3l-about-breadcrumb text-left">
    <div class="breadcrumb-bg breadcrumb-bg-about py-3">
      <div class="container grid-breadcrumb">
        <ul class="breadcrumbs-custom-path mt-md-2">
          <li><a href="index.php">Home</a></li>
          <li class="active"><span class="fa fa-angle-double-right mx-2" aria-hidden="true"></span> About Us </li>
        </ul>
      </div>
    </div>
  </section>
  <!-- //about breadcrumb -->
  <!-- /content-6-->
  <section class="w3l-content-6" id="about">
    <!-- /content-6-main-->
    <div class="content-6-mian py-5">
      <div class="container py-lg-5 py-md-4">
        <div class="content-info-in row">
          <div class="content-gd col-lg-6 pr-lg-4">
            <div class="title-content text-left mb-sm-4 mb-3">
              <h3 class="subhny-title">About Us</h3>
              <h3 class="hny-title"> </h3>
            </div>
            <p><b>Easy To Use & Low Cost
To start your Restaurant Business online is very easy with Foodchow. Just Few Minutes and you are ready to start..

 Fast and Easy to Setup
 Start Ordering in Minutes
 No Technical Expertise Required
 Easy Pricing</p></b>
          </div>
          <div class="content-gd col-lg-3 col-6 pl-lg-4 pl-lg-5 mt-lg-0 mt-md-5 mt-4">
            <img src="assets/images/s1.jpg" alt="about" class="radius-image img-fluid">
          </div>
          <div class="content-gd col-lg-3 col-6 pl-lg-4 pl-lg-5 mt-lg-0 mt-md-5 mt-4">
            <img src="assets/images/s2.jpg" alt="about" class="radius-image img-fluid">
          </div>
        </div>
        <p class="mt-4">
          Everybody needs food to eat. Some people enjoy eating in a restaurant, and some people enjoy making their own meals at home. There are many kinds of food that we can buy, so we can taste the different styles we want, and try foods from different countries. In America, it is very easy for us to find special food to eat because people from many different countries have opened their style restaurant. If we have enough money to spend we can eat many, many, kinds of meals. We can invite our friends to try them. It is very convenient, so many people want to come here 
</p>
      </div>
  </section>
  <!-- //content-6-->
    <!--/w3l-grids-3-->
  <section class="w3l-grids-3 py-5">
    <div class="container py-lg-5 py-md-4">
        <div class="row bottom-ab-grids">
          <div class="col-lg-6 bottom-right-grids mb-lg-0 mb-5">
            <img src="assets/images/pic5.png" alt="" class="img-fluid">
           </div>
            <div class="col-lg-6 bottom-ab-left pl-lg-5">
                <span class="subhny-title mb-2">Faster than light</span>
                <h3 class="hny-title mb-4">Why Choose Us online food order..</h3>
               <b> <p class="">The convenience of being able to order food from anywhere and anytime. The convenience of bringing your services to their doorstep.. </p></b>
                <ul class="cont-4 mt-4">
                    <li><span class="fa fa-check"></span>People have moved on from ordering offline to ordering online because it is easy, convenient and completely transparent.</li>
                    <li><span class="fa fa-check"></span>They can finally say goodbye to the hustle and bustle generated by the old ways of food ordering.</li>
                    <li><span class="fa fa-check"></span>Restaurant owners around the world who are racing to capture new customers have already jumped on board of the online delivering trend.</li>
                </ul>
                <a href="about.php" class="btn btn-style btn-primary mt-lg-5 mt-4">Read More <span class="fa fa-chevron-right"></span></a>
            </div>
           
        </div>
    </div>
</section>
  <!--//w3l-grids-3-->
  <!--/team-sec-->
  <section class="w3l-team-main" id="team">
    <div class="team py-5">
      <div class="container py-lg-5">
        <h3 class="subhny-title text-center">Team</h3>
        <h3 class="hny-title text-center mb-4">Behind the taste</h3>
        <div class="row team-row mt-md-5 mt-4">
          <div class="col-lg-3 col-6 team-wrap">
            <div class="team-member text-center">
              <div class="team-img">
                <img src="assets/images/team1.jpg" alt="" class="radius-image">
                <div class="overlay-team">
                  <div class="team-details text-center">
                    <div class="socials mt-20">
                      <a href="#url">
                        <span class="fa fa-facebook-f"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-twitter"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-instagram"></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a href="#url" class="team-title">Mickel Zaman</a>
              <p>Chief chef</p>
            </div>
          </div>
          <!-- end team member -->
          <div class="col-lg-3 col-6 team-wrap">
            <div class="team-member text-center">
              <div class="team-img">
                <img src="assets/images/team3.jpg" alt="" class="radius-image">
                <div class="overlay-team">
                  <div class="team-details text-center">
                    <div class="socials mt-20">
                      <a href="#url">
                        <span class="fa fa-facebook-f"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-twitter"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-instagram"></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a href="#url" class="team-title">Paul Croves</a>
              <p>Chief chef</p>
            </div>
          </div>
          <!-- end team member -->

          <div class="col-lg-3 col-6 team-wrap mt-lg-0 mt-5">
            <div class="team-member last text-center">
              <div class="team-img">
                <img src="assets/images/team2.jpg" alt="" class="radius-image">
                <div class="overlay-team">
                  <div class="team-details text-center">
                    <div class="socials mt-20">
                      <a href="#url">
                        <span class="fa fa-facebook-f"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-twitter"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-instagram"></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a href="#url" class="team-title">Ricardo Spencer</a>
              <p>Chief chef</p>
            </div>
          </div>
          <!-- end team member -->

          <div class="col-lg-3 col-6 team-wrap mt-lg-0 mt-5">
            <div class="team-member last text-center">
              <div class="team-img">
                <img src="assets/images/team4.jpg" alt="" class="radius-image">
                <div class="overlay-team">
                  <div class="team-details text-center">
                    <div class="socials mt-20">
                      <a href="#url">
                        <span class="fa fa-facebook-f"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-twitter"></span>
                      </a>
                      <a href="#url">
                        <span class="fa fa-instagram"></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a href="#url" class="team-title">Marko Dugonji</a>
              <p>Chief chef</p>
            </div>
          </div>
          <!-- end team member -->

        </div>
        <div class="w3l-skillshny-6 mt-5 pt-lg-5">
          <div class="row">
            <div class="col-lg-6 pr-lg-4">
              <div class="progress-info info1">
                <h6 class="progress-tittle">New Appetizers <span class="">80%</span></h6>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 80%"
                    aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                  </div>
                </div>
              </div>
              <div class="progress-info info2">
                <h6 class="progress-tittle">Inauguration <span class="">95%</span>
                </h6>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 95%"
                    aria-valuenow="95" aria-valuemin="0" aria-valuemax="100">
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6 pl-lg-4">
              <div class="progress-info info3">
                <h6 class="progress-tittle">Fresh Ingredients <span class="">75%</span></h6>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 75%"
                    aria-valuenow="95" aria-valuemin="0" aria-valuemax="100">
                  </div>
                </div>
              </div>
              <div class="progress-info info4 mb-0">
                <h6 class="progress-tittle">Facilities <span class="">85%</span></h6>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 85%"
                    aria-valuenow="95" aria-valuemin="0" aria-valuemax="100">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
</asp:Content>

